### ISSUE TITLE
Unable to PXE boot VMs with TripleO, out of date PXE 

### ISSUE THREAD

**Issue by timolow** [xcp-ng-rpms/ipxe#1]
I have converted my lab from VMware to XCP-ng 5.98, I am trying to get my Openstack (TripleO) lab deployed again I am hitting a snag in the PXE version of the Xen guest. Is there any way to get PXE upgraded for the guest VMs? When the VMs attempt to PXE boot they spam "Unrecognized Option --timeout" and refuses to boot. https://bugzilla.redhat.com/show_bug.cgi?id=1343649

**Comment by stormi** [comment]
Hi. There's no easy *and supported* way to update it at the moment. For some reasons, we have been stuck for an old version for some time and I don't know yet when we can upgrade it.

Have you tried the workaround from this comment? https://bugzilla.redhat.com/show_bug.cgi?id=1343649#c31

**Comment by timolow** [comment]
No joy on the fix, that fix was ages ago in Openstack terms, a lot as changed since then.

**Comment by stormi** [comment]
Could you open an issue at https://github.com/xcp-ng/xcp/issues?

Also, could you provide more context about the whole setup, why the VM's ipxe is used in this context, and whether this is a common use case? I don't know much about openstack and TripleO myself.

**Comment by timolow** [comment]
Created issue: https://github.com/xcp-ng/xcp/issues/559

**Comment by stormi** [comment]
Thanks. Closing this one to manage it only in one place.
